### ISSUE TITLE
Error building because of redefinition of typedef opk_vmlmc_t

### ISSUE THREAD

**Issue by tanish-satoor** [emmt/OptimPack.jl#1]
Error while building on OS X 10.11.4:

```
Making all in src
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT vmlmc.lo -MD -MP -MF .deps/vmlmc.Tpo -c -o vmlmc.lo vmlmc.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT vmlmc.lo -MD -MP -MF .deps/vmlmc.Tpo -c vmlmc.c  -fno-common -DPIC -o .libs/vmlmc.o
vmlmc.c:41:27: error: redefinition of typedef 'opk_vmlmc_t'
optimpack.h:1373:27: note: previous declaration of 'opk_vmlmc_t' was here
make[2]: *** [vmlmc.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I was able to fix this and build successfully by removing the typedef on line 44 of `vmlmc.c`

Here is the full [install log.](https://github.com/emmt/OptimPack.jl/files/346437/log.txt)

**Comment by Lightjohn** [comment]
First, thank you for posting the issue. I tried on my side on there is no problem on linux and I don't have a mac to test.
Can I have some context ? Was it the first install of OptimPack or did you already have had a previous version ? Did you try a new version in the git before ?

Thanks for any answer.

**Comment by tanish-satoor** [comment]
I tried to install using `Pkg.add()` in Julia, I had no previous version installed. It seems multiple typedefs are [allowed in C11 but not in C99.](http://stackoverflow.com/a/8595191)

It's possible our GCCs use different default C standards. Maybe `-std=c11` should be explicitly specified when compiling?

**Comment by Lightjohn** [comment]
I tried with a mac under snow leopard and there was the bug but I was not able to reproduce it on linux even by adding -std=c{89,90,99,11}, I even tried with gcc 4.7 but no error. Just to know, what is the current gcc version in mac os 10.11 ? (with snow leopard, std=gnu11 is not an option, because gcc is too old).
But I think the better will be to remove this line.

**Comment by emmt** [comment]
In principle, the issue has been fixed. Thanks for finding this!
