### ISSUE TITLE
Finding the C library

### ISSUE THREAD

**Issue by fabienbaron** [emmt/OptimPack.jl#3]
Currently the devel branch of OptimPack.jl has:
const opklib = joinpath(ENV["HOME"],"apps/lib/libopk.so.1.0.0")

It seems to me that it should point to this instead ? :
const opklib = string(Pkg.dir(),"/OptimPack/deps/usr/lib/libopk.so")

**Comment by emmt** [comment]
The devel branch no longer exists (all features are already in master) and uses BinDeps to manage the library.
