### ISSUE TITLE
Installation failed on Win10 (failed on Julia 1.2.0 and 1.3.0-rc4.1)

### ISSUE THREAD

**Issue by WT215** [emmt/OptimPack.jl#6]
Hi,

I tried to install the OptimPack but failed:

`julia> Pkg.add("OptimPack")
  Updating registry at `C:\Users\wt215\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\wt215\.julia\environments\v1.3\Project.toml`
  [04a3d532] + OptimPack v1.0.0
  Updating `C:\Users\wt215\.julia\environments\v1.3\Manifest.toml`
  [34da2185] + Compat v2.2.0
  [04a3d532] + OptimPack v1.0.0
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 

julia> using OptimPack
[ Info: Precompiling OptimPack [04a3d532-ba69-5937-989a-472689bdb720]
ERROR: LoadError: OptimPack not properly installed.  Please run Pkg.build("OptimPack")
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\wt215\.julia\packages\OptimPack\1ipTV\src\OptimPack.jl:32
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1105
 [5] include(::Module, ::String) at .\Base.jl:31
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:330 [inlined]
 [8] eval(::Expr) at .\client.jl:433
 [9] top-level scope at .\none:3
in expression starting at C:\Users\wt215\.julia\packages\OptimPack\1ipTV\src\OptimPack.jl:32
ERROR: Failed to precompile OptimPack [04a3d532-ba69-5937-989a-472689bdb720] to C:\Users\wt215\.julia\compiled\v1.3\OptimPack\lDOtl_ZMlJh.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917

julia> Pkg.build("OptimPack")
  Building OptimPack → `C:\Users\wt215\.julia\packages\OptimPack\1ipTV\deps\build.log`
┌ Error: Error building `OptimPack`:
│ ERROR: LoadError: IOError: could not spawn `make EXT=dll`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
│  [2] setup_stdios(::Base.var"#558#559"{Cmd}, ::Array{Any,1}) at .\process.jl:112
│  [3] _spawn at .\process.jl:111 [inlined]
│  [4] #run#569(::Bool, ::typeof(run), ::Cmd) at .\process.jl:439
│  [5] run(::Cmd) at .\process.jl:438
│  [6] top-level scope at C:\Users\wt215\.julia\packages\OptimPack\1ipTV\deps\build.jl:5
│  [7] include at .\boot.jl:328 [inlined]
│  [8] include_relative(::Module, ::String) at .\loading.jl:1105
│  [9] include(::Module, ::String) at .\Base.jl:31
│  [10] include(::String) at .\client.jl:432
│  [11] top-level scope at none:5
│ in expression starting at C:\Users\wt215\.julia\packages\OptimPack\1ipTV\deps\build.jl:2
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
false`

I also tried other path to install julia and then the package, but got the same error. 

Many thanks in advance!

**Comment by emmt** [comment]
Hi, 

Thanks for reporting this. The error seems to be when the build process attempts to compile the C code of [OptimPack](https://github.com/emmt/OptimPack). 

I never checked whether [OptimPack](https://github.com/emmt/OptimPack) shared C library can compile on Windows. In principle there is nothing special in this library that should prevent it. But I have to spend some time to find out how to build and install shared C library in Windows (I am a Linux user). I know that's possible!

Looking at the error message, it seems that the `make` command is not found. Make sure you have installed it on your system along with a complier.

If you cannot manage to compile OptimPack alone, another possibility would be for me to provide a precompiled library for various platforms. But, at the end I still have to learn how to do that on Windows.

I also have comitted  [OptimPackNextGen.jl](https://github.com/emmt/OptimPackNextGen.jl) which provides some of the algorithms of OptimPack in pure Julia. For now, there are still some dependencies on compiled C code (all the Powell methods) but if you only need VMLMB which is purely Julia code it should not be too difficult to make it available. For instance I could cut OptimPackNextGen in two packages: one for the pure Julia parts and the other with Powell methods.

In any cases, I would be happy to help as having this package usable under Windows is a strong motivation!

Let me know what you think.

**Comment by WT215** [comment]
@emmt Thank you for your reply! 

I would like to use `spectral project gradient ` method from `OptimPack`.  I will have a try the `OptimPackNextGen.jl`.

Thank you for developing this package!

**Comment by emmt** [comment]
Hello @WT215,
I have build precompiled C libraries of **OptimPack** for different architectures (see [here](https://github.com/emmt/OptimPack/releases/latest)) and manage to have the Julia wrappers in **OptimPack.jl** uses these libraries if possible. It seems to work for Windows (see the tests [here](https://ci.appveyor.com/project/emmt/optimpack-jl)). It is not yet an official version, so if you want to test this you'll have to make sure to use the **master** branch of **OptimPack.jl**. This is easy, from a Julia session, press ] to enter the Pkg REPL and type the following command:
```julia
(...) pkg> add OptimPack#master
```
Let me know if it works for you.

**Comment by WT215** [comment]
Hi @emmt,

Thanks a lot! I can install it on Win10 successfully!

Best wishes,
Wenhao
