### ISSUE TITLE
A toy example for spg2 function

### ISSUE THREAD

**Issue by WT215** [emmt/OptimPack.jl#7]
Hi,

Would you mind adding a toy example for illustrating how to use `spg2` please?  The explanation below is still too vague for me to understand:
```
function fg!(x, g)
  g[...] = gradient_at(x)
  return function_value_at(x)
end
function prj!(xp, x)
  xp[...] = projection_of(x)
end
```

Is it as the same as the `spg` function from the R package `BB`?

Thank you very much!

**Comment by WT215** [comment]
Also is it possible for user to just specify the lower limit and upper limit instead of projection function `prj!`? The former is easier to code.

**Comment by emmt** [comment]
These are both very good ideas. I am working on them!

**Comment by emmt** [comment]
It was a quite a piece of work! But this was very beneficial:
- a couple of bugs had to be fixed;
- the API of `OptimPack.jl` is better designed with `DenseVariable` behaving like regular Julia arrays;
- a complete example of using the Spectral Projected Gradient method is in `test/spg2-tests.jl`;
- the `spg2` method is fully documented.

**Comment by WT215** [comment]
@emmt  I appreciate for your help!
