### ISSUE TITLE
Not working on Julia 1.7

### ISSUE THREAD

**Issue by DeVerMyst** [emmt/OptimPack.jl#9]
Hello Eric

On dirait qu'OptimPack ne marche pas sur Julia 1.7 et tous les changement avec les modules
Amitié 

Antony

**Comment by emmt** [comment]
Hello Antony,
I have just checked that it does work with Julia-1.7
Can you be more specific?
Cheers,
Éric

**Comment by DeVerMyst** [comment]
Hello Eric, 

I probably got a bug in this case. I hadn't used julia from long time I guess I need to clean my system :) 
I close the issue 
Cheers,
Antony
